#!/usr/bin/env python3
"""
Export pypinyin's pinyin_dict.json → C++ header for binary search.

Output format:
  - PINYIN_CP[] : sorted uint32_t codepoints
  - PINYIN_DATA : contiguous null-terminated UTF-8 pinyin strings
  - PINYIN_OFFSET[] : uint32_t offsets into PINYIN_DATA (one per codepoint)

Binary search on PINYIN_CP[], then use the index to find the pinyin string.

Only the FIRST (most common) pronunciation per character is kept.
Tone diacritics → TONE3 numeric form (e.g. 'zhǐ' → 'zhi3').
Uses pypinyin's own to_tone3() for correct conversion.
"""

import json
import os
import sys

# Use pypinyin's built-in tone conversion
from pypinyin.contrib.tone_convert import to_tone3


def pinyin_to_tone3(py_str: str) -> str:
    """Convert pinyin with diacritic tones to tone3 numeric form.

    Examples: 'zhǐ' → 'zhi3', 'hǎo' → 'hao3', 'lǜ' → 'lv3'
    Uses pypinyin's own to_tone3() for accuracy.
    v_to_u=False keeps 'v' for ü (needed by our G2P code).
    """
    return to_tone3(py_str, neutral_tone_with_five=True, v_to_u=False)


def _find_dict_path() -> str:
    """Locate pypinyin's bundled pinyin_dict.json, or exit if not found."""
    here = os.path.dirname(__file__)
    candidates = [
        os.path.join(
            here, *prefix, ".venv", "lib", "python3.12",
            "site-packages", "pypinyin", "pinyin_dict.json",
        )
        for prefix in (("..", ".."), ("..",))
    ]
    for p in candidates:
        if os.path.exists(p):
            return p

    print("Error: pinyin_dict.json not found.", file=sys.stderr)
    sys.exit(1)


def _build_entries(raw_dict: dict) -> list[tuple[int, str]]:
    """Build sorted (codepoint, first_pinyin_tone3) entries, skipping empties."""
    entries = []
    skipped = 0
    for dec_cp, pinyin_str in raw_dict.items():
        first_pinyin = pinyin_str.split(",")[0].strip()
        if not first_pinyin:
            skipped += 1
            continue
        entries.append((int(dec_cp), pinyin_to_tone3(first_pinyin)))

    entries.sort(key=lambda x: x[0])
    print(f"Prepared {len(entries)} entries (skipped {skipped} empty)")
    return entries


def _write_header(out_path: str, entries: list[tuple[int, str]]) -> int:
    """Write the C++ header for `entries`. Returns the data blob size in bytes."""
    data_parts = []
    offsets = []
    offset = 0
    for _, pinyin in entries:
        encoded = pinyin.encode("utf-8")
        offsets.append(offset)
        data_parts.append(encoded)
        data_parts.append(b"\0")
        offset += len(encoded) + 1

    n_entries = len(entries)
    full_data = b"".join(data_parts)
    data_size = len(full_data)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by tools/export_pinyin_dict.py — DO NOT EDIT\n")
        f.write(
            "// Pinyin dictionary: Unicode CP → pinyin TONE3 (binary searchable)\n\n"
        )
        f.write("#include <cstdint>\n#include <cstddef>\n\n")
        f.write("namespace kokopop::g2p::zh {\n\n")

        f.write(f"constexpr size_t PINYIN_DICT_SIZE = {n_entries};\n\n")

        f.write("// ── Codepoint index (sorted ascending) ──\n")
        f.write("static const uint32_t PINYIN_CP[] = {\n")
        for cp, _ in entries:
            f.write(f"    {cp},\n")
        f.write("};\n\n")

        f.write("// ── Byte offsets into PINYIN_DATA ──\n")
        f.write("static const uint32_t PINYIN_OFFSET[] = {\n")
        for off in offsets:
            f.write(f"    {off},\n")
        f.write("};\n\n")

        f.write("// ── Pinyin string data (null-terminated, UTF-8) ──\n")
        f.write("static const unsigned char PINYIN_DATA[] = {\n")
        for i in range(0, len(full_data), 16):
            chunk = full_data[i : i + 16]
            f.write("    ")
            f.write(", ".join(f"0x{b:02x}" for b in chunk))
            f.write(",\n")
        f.write("};\n\n")

        f.write(f'static_assert(sizeof(PINYIN_DATA) == {data_size}, "data size");\n')
        f.write(
            'static_assert(sizeof(PINYIN_CP) / sizeof(PINYIN_CP[0]) == PINYIN_DICT_SIZE, "cp size");\n'
        )
        f.write(
            'static_assert(sizeof(PINYIN_OFFSET) / sizeof(PINYIN_OFFSET[0]) == PINYIN_DICT_SIZE, "off size");\n\n'
        )

        f.write("} // namespace kokopop::g2p::zh\n")

    return data_size


def main():
    dict_path = _find_dict_path()
    print(f"Loading {dict_path}...")
    with open(dict_path, "r", encoding="utf-8") as f:
        raw_dict = json.load(f)
    print(f"Loaded {len(raw_dict)} raw entries")

    entries = _build_entries(raw_dict)

    out_dir = os.path.join(os.path.dirname(__file__), "..", "src", "synthesis", "g2p")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "pinyin_dict.h")

    print(f"Generating {out_path}...")
    data_size = _write_header(out_path, entries)

    print(f"Done! {len(entries)} entries, data blob: {data_size:,} bytes")
    print(f"Header file: {out_path}")


if __name__ == "__main__":
    main()
