cmake_minimum_required(VERSION 3.24)
# Run after the pinned host eSpeak build has generated its dictionaries.
# Codes are dictionary names (en includes en-gb/en-us; fr includes fr-fr).
if(NOT LANGUAGES)
  message(FATAL_ERROR "KOKOPOP_WEB_LANGUAGES must be all or dictionary codes such as en;fr")
endif()
if(NOT LANGUAGES STREQUAL "all")
  set(selected en ${LANGUAGES}) # eSpeak's default voice and English fallback
  foreach(lang IN LISTS selected)
    if(NOT lang MATCHES "^[a-z][a-z0-9_]*$" OR NOT EXISTS "${DATA_SOURCE}/${lang}_dict")
      message(FATAL_ERROR "Unknown eSpeak dictionary '${lang}' in KOKOPOP_WEB_LANGUAGES; use dictionary codes such as en;fr (not en-us)")
    endif()
  endforeach()
  # Include language-switch dependencies from the same pinned dictionary sources.
  # This also handles transitive switches (e.g. a non-English fallback language).
  set(pending ${selected})
  set(visited)
  while(pending)
    list(POP_FRONT pending lang)
    if(lang IN_LIST visited)
      continue()
    endif()
    list(APPEND visited "${lang}")
    file(GLOB sources "${DICT_SOURCE}/${lang}_*")
    foreach(source IN LISTS sources)
      file(READ "${source}" contents)
      string(REGEX MATCHALL "_\\^_[A-Za-z][A-Za-z-]*" switches "${contents}")
      foreach(switch IN LISTS switches)
        string(SUBSTRING "${switch}" 3 -1 dependency)
        string(TOLOWER "${dependency}" dependency)
        string(REGEX REPLACE "-.*$" "" dependency "${dependency}")
        if(EXISTS "${DATA_SOURCE}/${dependency}_dict" AND NOT dependency IN_LIST visited)
          list(APPEND selected "${dependency}")
          list(APPEND pending "${dependency}")
        endif()
      endforeach()
    endforeach()
  endwhile()
  list(REMOVE_DUPLICATES selected)
endif()

# Recreate the staging directory so narrowing a previous selection removes files.
file(REMOVE_RECURSE "${DATA_DEST}")
file(MAKE_DIRECTORY "${DATA_DEST}")
if(LANGUAGES STREQUAL "all")
  file(COPY "${DATA_SOURCE}/" DESTINATION "${DATA_DEST}")
else()
  foreach(common phondata phonindex phontab intonations)
    file(COPY "${DATA_SOURCE}/${common}" DESTINATION "${DATA_DEST}")
  endforeach()
  file(COPY "${DATA_SOURCE}/voices" DESTINATION "${DATA_DEST}")
  foreach(lang IN LISTS selected)
    file(COPY "${DATA_SOURCE}/${lang}_dict" DESTINATION "${DATA_DEST}")
  endforeach()
  file(GLOB_RECURSE definitions RELATIVE "${DATA_SOURCE}/lang" "${DATA_SOURCE}/lang/*")
  foreach(definition IN LISTS definitions)
    file(READ "${DATA_SOURCE}/lang/${definition}" contents)
    # eSpeak uses the first language's base code unless 'dictionary' overrides it.
    string(REGEX MATCH "(^|\n)language[ \t]+([a-zA-Z0-9_]+)" match "${contents}")
    set(dictionary "${CMAKE_MATCH_2}")
    string(REGEX MATCH "(^|\n)dictionary[ \t]+([a-zA-Z0-9_]+)" override "${contents}")
    if(override)
      set(dictionary "${CMAKE_MATCH_2}")
    endif()
    if(dictionary IN_LIST selected)
      get_filename_component(directory "${definition}" DIRECTORY)
      file(COPY "${DATA_SOURCE}/lang/${definition}" DESTINATION "${DATA_DEST}/lang/${directory}")
    endif()
  endforeach()
  message(STATUS "Web eSpeak dictionaries: ${selected}")
endif()
